#!../../bin/linux-x86_64/esys-sample
#+======================================================================
# $HeadURL: https://svnpub.iter.org/codac/iter/codac/dev/units/m-epics-iter-templates/tags/CODAC-CORE-4.1.0/templates/genericBoot/ioc/st.cmd $
# $Id: st.cmd 35402 2013-04-07 15:41:49Z zagara $
#
# Project       : CODAC Core System
#
# Description   : ITER ioc template EPICS start up file
#
# Author(s)     : This file was generated by CODAC development toolkit
#
# Copyright (c) : 2010-2013 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

< envPaths
< envSystem
< envUser

cd "${TOP}"

#############################################
## Register all support components         ##
#############################################

dbLoadDatabase "dbd/esys-sample.dbd"
esys_sample_registerRecordDeviceDriver pdbbase

#< "${TOP}/iocBoot/iocesys-sample/sddPreDriverConf.cmd"
< "${TOP}/iocBoot/iocesys-sample/userPreDriverConf.cmd"
#< "${TOP}/iocBoot/iocesys-sample/threadSchedulingConf.cmd"
< "${TOP}/iocBoot/iocesys-sample/dbToLoad.cmd"
#< "${TOP}/iocBoot/iocesys-sample/iocesys-sample-preSaveRestore.cmd"

#############################################
## IOC Logging                             ##
#############################################
iocLogInit

#############################################
## IOC initialization                      ##
#############################################
cd "${TOP}/db"
iocInit

#< "${TOP}/iocBoot/iocesys-sample/iocesys-sample-postSaveRestore.cmd"
#< "${TOP}/iocBoot/iocesys-sample/sddSeqToLoad.cmd"
#< "${TOP}/iocBoot/iocesys-sample/seqToLoad.cmd"
#< "${TOP}/iocBoot/iocesys-sample/sddPostDriverConf.cmd"
#< "${TOP}/iocBoot/iocesys-sample/userPostDriverConf.cmd"


